id: c69a3c641b38471281032d83b304b3a6
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_83-The_Questions_of_Bhadrapala_the_Merchant-v1
  language: bo
  author: ''
  volume: {}
